/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CaptainRouteImport } from './routes/captain'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptainIndexRouteImport } from './routes/captain.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsPastRouteImport } from './routes/tournaments.past'
import { Route as TournamentIdRouteImport } from './routes/tournament.$id'
import { Route as CaptainTeamTeamIdRouteImport } from './routes/captain.team.$teamId'
import { Route as AdminTournamentsNewRouteImport } from './routes/admin.tournaments.new'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'
import { Route as CaptainTeamTeamIdIndexRouteImport } from './routes/captain.team.$teamId.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AdminTournamentsIdTeamsRouteImport } from './routes/admin.tournaments.$id_.teams'
import { Route as AdminTournamentsIdLiveopsRouteImport } from './routes/admin.tournaments.$id_.liveops'
import { Route as AdminTournamentsIdAuditRouteImport } from './routes/admin.tournaments.$id_.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainRoute = CaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainIndexRoute = CaptainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaptainRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsPastRoute = TournamentsPastRouteImport.update({
  id: '/tournaments/past',
  path: '/tournaments/past',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIdRoute = TournamentIdRouteImport.update({
  id: '/tournament/$id',
  path: '/tournament/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainTeamTeamIdRoute = CaptainTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => CaptainRoute,
} as any)
const AdminTournamentsNewRoute = AdminTournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const CaptainTeamTeamIdIndexRoute = CaptainTeamTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaptainTeamTeamIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsIdTeamsRoute = AdminTournamentsIdTeamsRouteImport.update({
  id: '/tournaments/$id_/teams',
  path: '/tournaments/$id/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsIdLiveopsRoute =
  AdminTournamentsIdLiveopsRouteImport.update({
    id: '/tournaments/$id_/liveops',
    path: '/tournaments/$id/liveops',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTournamentsIdAuditRoute = AdminTournamentsIdAuditRouteImport.update({
  id: '/tournaments/$id_/audit',
  path: '/tournaments/$id/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/captain': typeof CaptainRouteWithChildren
  '/login': typeof LoginRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/tournaments/past': typeof TournamentsPastRoute
  '/admin/': typeof AdminIndexRoute
  '/captain/': typeof CaptainIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/captain/team/$teamId': typeof CaptainTeamTeamIdRouteWithChildren
  '/admin/tournaments/$id/audit': typeof AdminTournamentsIdAuditRoute
  '/admin/tournaments/$id/liveops': typeof AdminTournamentsIdLiveopsRoute
  '/admin/tournaments/$id/teams': typeof AdminTournamentsIdTeamsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/captain/team/$teamId/': typeof CaptainTeamTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/tournaments/past': typeof TournamentsPastRoute
  '/admin': typeof AdminIndexRoute
  '/captain': typeof CaptainIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/admin/tournaments/$id/audit': typeof AdminTournamentsIdAuditRoute
  '/admin/tournaments/$id/liveops': typeof AdminTournamentsIdLiveopsRoute
  '/admin/tournaments/$id/teams': typeof AdminTournamentsIdTeamsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/captain/team/$teamId': typeof CaptainTeamTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/captain': typeof CaptainRouteWithChildren
  '/login': typeof LoginRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/tournaments/past': typeof TournamentsPastRoute
  '/admin/': typeof AdminIndexRoute
  '/captain/': typeof CaptainIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/tournaments/new': typeof AdminTournamentsNewRoute
  '/captain/team/$teamId': typeof CaptainTeamTeamIdRouteWithChildren
  '/admin/tournaments/$id_/audit': typeof AdminTournamentsIdAuditRoute
  '/admin/tournaments/$id_/liveops': typeof AdminTournamentsIdLiveopsRoute
  '/admin/tournaments/$id_/teams': typeof AdminTournamentsIdTeamsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/captain/team/$teamId/': typeof CaptainTeamTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/captain'
    | '/login'
    | '/tournament/$id'
    | '/tournaments/past'
    | '/admin/'
    | '/captain/'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/captain/team/$teamId'
    | '/admin/tournaments/$id/audit'
    | '/admin/tournaments/$id/liveops'
    | '/admin/tournaments/$id/teams'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/captain/team/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tournament/$id'
    | '/tournaments/past'
    | '/admin'
    | '/captain'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/admin/tournaments/$id/audit'
    | '/admin/tournaments/$id/liveops'
    | '/admin/tournaments/$id/teams'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/captain/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/captain'
    | '/login'
    | '/tournament/$id'
    | '/tournaments/past'
    | '/admin/'
    | '/captain/'
    | '/admin/tournaments/$id'
    | '/admin/tournaments/new'
    | '/captain/team/$teamId'
    | '/admin/tournaments/$id_/audit'
    | '/admin/tournaments/$id_/liveops'
    | '/admin/tournaments/$id_/teams'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/captain/team/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaptainRoute: typeof CaptainRouteWithChildren
  LoginRoute: typeof LoginRoute
  TournamentIdRoute: typeof TournamentIdRoute
  TournamentsPastRoute: typeof TournamentsPastRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain': {
      id: '/captain'
      path: '/captain'
      fullPath: '/captain'
      preLoaderRoute: typeof CaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/': {
      id: '/captain/'
      path: '/'
      fullPath: '/captain/'
      preLoaderRoute: typeof CaptainIndexRouteImport
      parentRoute: typeof CaptainRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/past': {
      id: '/tournaments/past'
      path: '/tournaments/past'
      fullPath: '/tournaments/past'
      preLoaderRoute: typeof TournamentsPastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$id': {
      id: '/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/tournament/$id'
      preLoaderRoute: typeof TournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain/team/$teamId': {
      id: '/captain/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/captain/team/$teamId'
      preLoaderRoute: typeof CaptainTeamTeamIdRouteImport
      parentRoute: typeof CaptainRoute
    }
    '/admin/tournaments/new': {
      id: '/admin/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/admin/tournaments/new'
      preLoaderRoute: typeof AdminTournamentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/captain/team/$teamId/': {
      id: '/captain/team/$teamId/'
      path: '/'
      fullPath: '/captain/team/$teamId/'
      preLoaderRoute: typeof CaptainTeamTeamIdIndexRouteImport
      parentRoute: typeof CaptainTeamTeamIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments/$id_/teams': {
      id: '/admin/tournaments/$id_/teams'
      path: '/tournaments/$id/teams'
      fullPath: '/admin/tournaments/$id/teams'
      preLoaderRoute: typeof AdminTournamentsIdTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$id_/liveops': {
      id: '/admin/tournaments/$id_/liveops'
      path: '/tournaments/$id/liveops'
      fullPath: '/admin/tournaments/$id/liveops'
      preLoaderRoute: typeof AdminTournamentsIdLiveopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$id_/audit': {
      id: '/admin/tournaments/$id_/audit'
      path: '/tournaments/$id/audit'
      fullPath: '/admin/tournaments/$id/audit'
      preLoaderRoute: typeof AdminTournamentsIdAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
  AdminTournamentsNewRoute: typeof AdminTournamentsNewRoute
  AdminTournamentsIdAuditRoute: typeof AdminTournamentsIdAuditRoute
  AdminTournamentsIdLiveopsRoute: typeof AdminTournamentsIdLiveopsRoute
  AdminTournamentsIdTeamsRoute: typeof AdminTournamentsIdTeamsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
  AdminTournamentsNewRoute: AdminTournamentsNewRoute,
  AdminTournamentsIdAuditRoute: AdminTournamentsIdAuditRoute,
  AdminTournamentsIdLiveopsRoute: AdminTournamentsIdLiveopsRoute,
  AdminTournamentsIdTeamsRoute: AdminTournamentsIdTeamsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CaptainTeamTeamIdRouteChildren {
  CaptainTeamTeamIdIndexRoute: typeof CaptainTeamTeamIdIndexRoute
}

const CaptainTeamTeamIdRouteChildren: CaptainTeamTeamIdRouteChildren = {
  CaptainTeamTeamIdIndexRoute: CaptainTeamTeamIdIndexRoute,
}

const CaptainTeamTeamIdRouteWithChildren =
  CaptainTeamTeamIdRoute._addFileChildren(CaptainTeamTeamIdRouteChildren)

interface CaptainRouteChildren {
  CaptainIndexRoute: typeof CaptainIndexRoute
  CaptainTeamTeamIdRoute: typeof CaptainTeamTeamIdRouteWithChildren
}

const CaptainRouteChildren: CaptainRouteChildren = {
  CaptainIndexRoute: CaptainIndexRoute,
  CaptainTeamTeamIdRoute: CaptainTeamTeamIdRouteWithChildren,
}

const CaptainRouteWithChildren =
  CaptainRoute._addFileChildren(CaptainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CaptainRoute: CaptainRouteWithChildren,
  LoginRoute: LoginRoute,
  TournamentIdRoute: TournamentIdRoute,
  TournamentsPastRoute: TournamentsPastRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
